# Generated by Django 5.0.6 on 2024-06-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mychats_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mychats',
            old_name='chats',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='mychats',
            old_name='frnd',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='mychats',
            old_name='me',
            new_name='sender',
        ),
    ]
